#!/bin/bash

OUT=jobs.md
IFS="
"
echo "" > $OUT

for F in $(ls -1)
do 
    echo $F
    [ $F = "$OUT" ] && continue
    [ $F = "proc" ] && continue
    echo "" >> $OUT
    echo "---" >> $OUT
    echo $F | sed 's/^[0-9]\+\. /Title: /' | sed 's/\.md$//' >> $OUT
    cat $F | sed 's/\*\*//g' >> $OUT
    echo "" >> $OUT
done
